[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
test_de = "8zcwVWLTk2eXqgpPj5CZqkcVBRLvaqa6GaVRbhn7yCay"

[programs.localnet]
test_de = "8zcwVWLTk2eXqgpPj5CZqkcVBRLvaqa6GaVRbhn7yCay"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/cj/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
