[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
test_de = "J2hD3qwZMr77ZPZWkbT5abK4TwgnVnPrxSx89Fo5Sxng"

[programs.localnet]
aaa = "FKYoRpWsZe7uUexpHFmqRq6RaqVExh74Fe9uyM7kqV2a"
claim = "DfuPTGawoHGdUpJaN47TTXCvhitNwYvkUuyRBxCV1oHF"
cliam = "4ngZcEacbv1RNfaGbGxtcdbVjGiKjC2fD6Acro9KASzL"
test_de = "J2hD3qwZMr77ZPZWkbT5abK4TwgnVnPrxSx89Fo5Sxng"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/cj/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/tactoe.ts"
 
